###
// check register user from Atlas

POST  http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "itai@gmail.com",
    "password": "itai111"
}

###
// check login user from Atlas

POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "nadavTheKing@gmail.com",
    "password": "crypto123"
}

###
// check login user from Atlas

POST  http://localhost:3000/auth/logout
Content-Type: application/json

{
    "email": "nadavTheKing@gmail.com",
    "password": "crypto123"
}

### 
// get all users from Atlas

GET http://localhost:3000/auth/users

###

// get all users by id from Atlas

GET http://localhost:3000/auth/624c7d3f345567a910980d93
