###
// check register user from Atlas

POST  http://localhost:3000/api/users/signup
Content-Type: application/json

{
    "email": "or@gmail.com",
    "password": "1111",
    "password_confirm": "1111",
    "firstName": "Or",
    "lastName": "Kravitz",
    "birthday": "8/2/1993",
    "phoneNumber": "054666789"}

###
// check login user from Atlas

POST  http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "nadavTheKing@gmail.com",
    "password": "crypto123"
}

###
// check login user from Atlas

POST  http://localhost:3000/auth/logout
Content-Type: application/json

{
    "email": "nadavTheKing@gmail.com",
    "password": "crypto123"
}

### 
// get all users from Atlas

GET http://localhost:3000/auth/users

###

// get all users by id from Atlas

GET http://localhost:3000/auth/624c7d3f345567a910980d93
